
#ifndef GRINREFLEX_APPLICATION_H
#define GRINREFLEX_APPLICATION_H

#include "stddef.h"
#include "stdint.h"

#ifdef __cplusplus
extern "C" {
#endif

#if defined(CONFIG_GRINREFLEX_JPEG_VIDEO)

#if defined(CONFIG_STM32_JPEG_RGB_FORMAT)
#if CONFIG_STM32_JPEG_RGB_FORMAT == 0
#define JPEG_COLOR_FORMAT LV_COLOR_FORMAT_ARGB8888
#elif CONFIG_STM32_JPEG_RGB_FORMAT == 1
#define JPEG_COLOR_FORMAT LV_COLOR_FORMAT_RGB888
#elif CONFIG_STM32_JPEG_RGB_FORMAT == 2
#define JPEG_COLOR_FORMAT LV_COLOR_FORMAT_RGB565
#elif CONFIG_STM32_JPEG_RGB_FORMAT == 3
#define JPEG_COLOR_FORMAT LV_COLOR_FORMAT_L8
#else
#error "CONFIG_STM32_JPEG_RGB_FORMAT is not supported"
#endif

#else
#define JPEG_COLOR_FORMAT LV_COLOR_FORMAT_RGB888
#endif /* defined(CONFIG_STM32_JPEG_RGB_FORMAT) */

#endif /* defined(CONFIG_GRINREFLEX_JPEG_VIDEO) */

#define GRAY_FRAME_WIDTH 80
#define GRAY_FRAME_HEIGHT 80


int init();

int loop();

#ifdef __cplusplus
}
#endif

#endif /* GRINREFLEX_APPLICATION_H */