

#pragma once

#if !defined(CONFIG_GRINREFLEX_JPEG_VIDEO)
#error "Not supported yet"
#endif

#if defined(CONFIG_STM32_JPEG_RGB_FORMAT)
#if CONFIG_STM32_JPEG_RGB_FORMAT == 0
#define FULL_FRAME_COLOR_FORMAT LV_COLOR_FORMAT_ARGB8888
#elif CONFIG_STM32_JPEG_RGB_FORMAT == 1
#define FULL_FRAME_COLOR_FORMAT LV_COLOR_FORMAT_RGB888
#elif CONFIG_STM32_JPEG_RGB_FORMAT == 2
#define FULL_FRAME_COLOR_FORMAT LV_COLOR_FORMAT_RGB565
#elif CONFIG_STM32_JPEG_RGB_FORMAT == 3
#define FULL_FRAME_COLOR_FORMAT LV_COLOR_FORMAT_L8
#else
#error "CONFIG_STM32_JPEG_RGB_FORMAT is not supported"
#endif

#else
#define FULL_FRAME_COLOR_FORMAT LV_COLOR_FORMAT_RGB888
#endif /* defined(CONFIG_STM32_JPEG_RGB_FORMAT) */

#define FULL_FRAME_WIDTH CONFIG_GRINREFLEX_VIDEO_WIDTH
#define FULL_FRAME_HEIGHT CONFIG_GRINREFLEX_VIDEO_HEIGHT

#define ROI_FRAME_WIDTH 320
#define ROI_FRAME_HEIGHT 240

#define THUMBNAIL_FRAME_WIDTH 80
#define THUMBNAIL_FRAME_HEIGHT 80

#define INPUT_PREPROCESS_OPENCV (0)
#define FULL_FRAME_FLIP_Y (0)