# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos/
    - name: origin
      url-base: https://github.com/cornway/

  projects:
    - name: zephyr
      remote: origin
      revision: roman/development-n6
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis_6    # required by the ARM port for Cortex-M
          - cmsis-dsp
          - hal_stm32
          - tflite-micro
          - lvgl
          - mbedtls
    - name: mcuboot
      remote: origin
      revision: roman/development
      path: bootloader/mcuboot